version: '3'
services:
  db:
    image: mdillon/postgis:10-alpine
    volumes: 
      - ./dhis:/db-backups/
      - db-data:/var/lib/postgresql/data
    command: postgres -c max_locks_per_transaction=100
    container_name: jostano-db
    environment:
      POSTGRES_USER: dhis
      POSTGRES_DB: jostano
      POSTGRES_PASSWORD: dhis
    networks: 
      - backend
  dhis-web:
    image: dhis2/core:2.33.0
    volumes:
      - ./config/dhis2_home/dhis.conf:/DHIS2_home/dhis.conf
    container_name: jostano-dhis
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks: 
      - backend
  app-web:
    image: nginx:latest
    build: 
      context: .
      dockerfile: dockerfile
    container_name: jostano-web
    ports:
      - "4300:80"
    depends_on: 
      - dhis-web
    networks:
      - backend
networks:
  backend:
    driver: "bridge"
volumes:
  db-data:
    driver: local
