version: '3'
services:
  db:
    image: mdillon/postgis:10-alpine
    volumes: 
      - ./dhis:/db-backups/
      - db-data:/var/lib/postgresql/data
    command: postgres -c max_locks_per_transaction=100
    container_name: zess-db
    environment:
      POSTGRES_USER: dhis
      POSTGRES_DB: zess
      POSTGRES_PASSWORD: dhis
    networks: 
      - backend
  web:
    image: dhis2/core:2.33.0
    volumes:
      - ./config/dhis2_home/dhis.conf:/DHIS2_home/dhis.conf
    container_name: zess-dhis
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks: 
      - backend
networks:
  backend:
    driver: "bridge"
volumes:
  db-data:
    driver: local
